version: 2

sources:
  - name: intermediate
    description: Banco de replica do AdventureWorks
    schema: adventureworks_intermediate
    tables:
      - name: int_dim_product

      - name: int_fct_sales