version: 2

sources:
  - name: intermediate
    description: Banco de replica do AdventureWorks
    schema: adventureworks_intermediate
    
    tables:
      - name: int_dim_product

      - name: int_fct_sales

      - name: int_dim_customer

      - name: int_dim_reason

      - name: int_dim_sales_person