version: 2

sources:
  - name: adventure
    description: Banco de replica do AdventureWorks
    schema: adventureworks
    tables:
      - name: raw_product_product

      - name: raw_sales_currency_rate

      - name: raw_sales_customer

      - name: raw_sales_order_detail

      - name: raw_sales_order_header

      - name: raw_sales_person

      - name: raw_sales_store

      - name: raw_sales_territory