version: 2

sources:
  - name: stg
    description: Banco de replica do AdventureWorks
    schema: adventureworks_stg
    tables:
      - name: stg_product_product

      - name: stg_sales_currencyrate

      - name: stg_sales_customer

      - name: stg_sales_orderdetail

      - name: stg_sales_orderheader

      - name: stg_sales_salesperson

      - name: stg_sales_store

      - name: stg_sales_territory

      - name: stg_person_person
